targets:
  $default:
    builders:
      drift_dev:
        options:
           apply_converters_on_variables: true
           sql:
             dialect: sqlite
             options:
               version: "3.38"
          